# 0-D Arrays

In [9]:
import numpy as np
arry=np.array(42)
print(arry)

42


# 1-D Arrays

In [12]:
import numpy as np
arry=np.array([1,2,3,4,5])
print(arry)

[1 2 3 4 5]


# 2-D Arrays

In [23]:
import numpy as np
arry=np.array([[1,2,3],[1,2,3]])
print(arry)
print(type(arry))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


# 3-D arrays

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

In [1]:
a={1,1,1,1,1,22,4}
b=0
for i in a:
    for j in a:
        if i==j:
            b

{1, 4, 22}


In [8]:
for i in range(5):
    if i%2==0:
        print(i)
    else:
        print("hello")

SyntaxError: invalid syntax (747850867.py, line 3)